databases:
  - name: asobi_DB
    databaseName: asobi_db_cgtb
    user: asobi
    region: singapore

services:
  - type: web
    name: asobi
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asobi_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

